name = "notion-blog-worker"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[vars]
NOTION_API_SECRET = ""
DATABASE_ID = ""

[triggers]
crons = ["0 6,18 * * *"]  # UTC 时间，对应北京时间 14:00 和 02:00

[build]
command = "npm run build" 