name = "notion-blog-worker"
compatibility_date = "2024-01-01"
main = "src/index.ts"

[vars]
NOTION_API_SECRET = ""  # 将在部署时通过环境变量注入
DATABASE_ID = ""       # 将在部署时通过环境变量注入

[triggers]
crons = ["0 0,12 * * *"]  # 每天 UTC 0:00 和 12:00 运行

[build]
command = "npm run build"  # 使用 worker 的构建命令 