name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'  # UTC 时间，对应北京时间 8:00 和 20:00

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'npm'

      # 创建必要的目录
      - name: Create directories
        run: |
          mkdir -p tmp
          mkdir -p public/notion
          mkdir -p worker

      # 安装依赖
      - name: Install dependencies
        run: |
          npm install
          cd worker && npm init -y
          npm install @cloudflare/workers-types wrangler @notionhq/client --save-dev
          cd ..

      # 测试 Notion 连接
      - name: Test Notion Connection
        run: |
          echo "Testing Notion connection..."
          curl -X POST "https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_SECRET }}" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json"

      # 构建 worker
      - name: Build worker
        run: |
          cd worker
          npx wrangler deploy src/index.ts --dry-run --outdir dist
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}

      # 获取 Notion 内容
      - name: Fetch Notion content
        run: npm run cache:fetch
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CACHE_CONCURRENCY: "5"

      - name: Build
        run: npm run build:cached
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CF_PAGES: true

      # 部署 worker
      - name: Deploy worker
        run: |
          curl --fail-with-body -X PUT \
            https://api.cloudflare.com/client/v4/accounts/${{ steps.fetch_account_id.outputs.account_id }}/workers/scripts/notion-blog-worker/content \
            --header 'Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}' \
            -F 'index.js=@worker/dist/index.js;type=application/javascript+module' \
            -F 'metadata={"main_module": "index.js"}'

      # 部署页面
      - name: Deploy to Pages
        run: |
          npx wrangler pages deploy dist \
            --project-name=astro-notion-blog \
            --branch=main \
            --commit-hash=${{ github.sha }} \
            --commit-message="${{ github.event.head_commit.message || 'Manual deployment' }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ steps.fetch_account_id.outputs.account_id }}