name: Deploy to Cloudflare Pages

on:
  # 代码推送时触发
  push:
    branches: [ main ]
  # 支持手动触发
  workflow_dispatch:
  # 定时触发（每天早8点和晚8点）
  schedule:
    - cron: '0 0,12 * * *'  # UTC 时间，对应北京时间 8:00 和 20:00

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 自动获取 Account ID
      - name: Fetch Account ID
        id: fetch_account_id
        run: |
          ACCOUNT_ID=$(curl -X GET "https://api.cloudflare.com/client/v4/accounts" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.result[0].id')
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "Account ID: $ACCOUNT_ID"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'npm'

      # 创建必要的目录
      - name: Create directories
        run: |
          mkdir -p tmp
          mkdir -p public/notion

      - name: Install dependencies
        run: npm install

      # 获取 Notion 内容
      - name: Fetch Notion content
        run: npm run cache:fetch
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CACHE_CONCURRENCY: "5"

      - name: Build
        run: npm run build:cached
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CF_PAGES: true

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.ACCOUNT_ID }}
          projectName: astro-notion-blog
          directory: dist
          branch: main