name: Deploy to Cloudflare

on:
  push:
    branches: ['main']
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'  # UTC 0:00 and 12:00 (北京时间 8:00 和 20:00)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.6.4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'
          cache: 'npm'

      # 获取 Cloudflare Account ID
      - name: Fetch Account ID
        id: fetch_account_id
        run: |
          if [[ -n "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]]; then
            ACCOUNT_ID="${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
            echo "Using provided CLOUDFLARE_ACCOUNT_ID from secrets."
          else
            ACCOUNT_ID=$(curl -X GET "https://api.cloudflare.com/client/v4/accounts" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
              -H "Content-Type:application/json" | jq ".result[0].id" -r)
            if [[ "$ACCOUNT_ID" == "null" ]]; then
              echo "Failed to get an account id, please make sure you have set up CLOUDFLARE_API_TOKEN correctly!"
              exit 1
            fi
          fi
          echo 'account_id='$ACCOUNT_ID >> $GITHUB_OUTPUT
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Build Blog
        run: npm run build:cached
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}

      # 使用 Terraform 部署
      - name: Deploy using Terraform
        run: |
          terraform init
          terraform apply -auto-approve -input=false
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_CLOUDFLARE_ACCOUNT_ID: ${{ steps.fetch_account_id.outputs.account_id }}
          TF_VAR_NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          TF_VAR_DATABASE_ID: ${{ secrets.DATABASE_ID }}

      # 使用 wrangler 部署页面
      - name: Deploy to Pages
        run: |
          npx wrangler pages deploy dist --project-name astro-notion-blog
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ steps.fetch_account_id.outputs.account_id }} 