name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'  # 每天 UTC 0:00 和 12:00 运行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 自动获取 Account ID
      - name: Fetch Account ID
        id: fetch_account_id
        run: |
          ACCOUNT_ID=$(curl -X GET "https://api.cloudflare.com/client/v4/accounts" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.result[0].id')
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "Account ID: $ACCOUNT_ID"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      # 配置 npm
      - name: Configure npm
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set fetch-retry-maxtimeout 600000
          npm config set fetch-retry-mintimeout 10000
          npm config set fetch-retries 5

      # 安装依赖（带重试）
      - name: Install dependencies
        run: |
          for i in {1..3}; do
            npm install && break
            echo "Retry $i..."
            sleep 5
          done

      # 创建必要的目录
      - name: Create directories
        run: |
          mkdir -p tmp
          mkdir -p public/notion

      # 测试 Notion 连接
      - name: Test Notion API
        run: |
          echo "Testing Notion API..."
          curl -X POST "https://api.notion.com/v1/databases/${{ secrets.DATABASE_ID }}/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_SECRET }}" \
            -H "Notion-Version: 2022-06-28" \
            -H "Content-Type: application/json" \
            -d '{
              "filter": {
                "property": "Published",
                "checkbox": {
                  "equals": true
                }
              }
            }' | jq .

      - name: Fetch Notion content
        run: npm run cache:fetch
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CACHE_CONCURRENCY: "5"
          DEBUG: "true"  # 启用调试输出

      - name: Build
        run: npm run build:cached
        env:
          NOTION_API_SECRET: ${{ secrets.NOTION_API_SECRET }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          CF_PAGES: true
          SITE_URL: 'https://astro-notion-blog.pages.dev'
          DEBUG: "true"  # 启用调试输出

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.ACCOUNT_ID }}
          projectName: astro-notion-blog
          directory: dist
          branch: main